
services:

  server:
    build: ./server
    container_name: devops2025-server
    ports:
      - "8000:8000"   # Django
      - "2222:22"     # SSH
    volumes:
      - ./server:/app
    command: bash -c "/usr/sbin/sshd && poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - rabbitmq

  client:
    build: ./client
    container_name: devops2025-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev -- --host
    depends_on:
      - server

  nginx:
    build: ./nginx
    container_name: devops2025-nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - monitoring

  db:
    image: postgres:15
    container_name: devops2025-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: devops2025-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    image: prom/prometheus
    container_name: devops2025-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  monitoring:
    image: grafana/grafana
    container_name: devops2026-monitoring
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  grafana-data:


