[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["rabab <you@example.com>"]
packages = [{ include = "config" }]

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

